# Generated by Django 3.1.1 on 2020-10-22 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imageID', models.CharField(max_length=34, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('inspectionID', models.CharField(max_length=34, primary_key=True, serialize=False)),
                ('inspectionDate', models.CharField(max_length=30)),
                ('exteriorInspection', models.CharField(max_length=100)),
                ('interiorInspection', models.CharField(max_length=100)),
                ('hoodTrunkInspection', models.CharField(max_length=100)),
                ('helmetInpsection', models.CharField(max_length=100)),
                ('ExteriorApproval', models.BooleanField(default=False)),
                ('InteriorApproval', models.BooleanField(default=False)),
                ('HoodApproval', models.BooleanField(default=False)),
                ('TrunkApproval', models.BooleanField(default=False)),
                ('Other', models.CharField(max_length=140)),
                ('Verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UUID', models.CharField(max_length=34, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=30)),
                ('middleInitial', models.CharField(max_length=1)),
                ('lastName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('waiverID', models.CharField(max_length=34, primary_key=True, serialize=False)),
                ('waiverDate', models.CharField(max_length=30)),
                ('waiverComplete', models.CharField(max_length=100)),
                ('UUID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.user')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('VIN', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('vehicleYear', models.IntegerField()),
                ('vehicleMake', models.CharField(max_length=50)),
                ('vehicleModel', models.CharField(max_length=50)),
                ('UUID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.user')),
                ('inspectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.inspection')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='VIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.vehicle'),
        ),
        migrations.AddField(
            model_name='user',
            name='imageID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.image'),
        ),
        migrations.AddField(
            model_name='user',
            name='waiverID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.waiver'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='VIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.vehicle'),
        ),
    ]
