# Generated by Django 3.1.2 on 2020-10-23 00:42

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import pages.db_validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='TIUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('inspectionID', models.CharField(max_length=34, primary_key=True, serialize=False)),
                ('inspectionDate', models.CharField(max_length=30)),
                ('exteriorInspection', models.CharField(max_length=100)),
                ('interiorInspection', models.CharField(max_length=100)),
                ('hoodTrunkInspection', models.CharField(max_length=100)),
                ('helmetInpsection', models.CharField(max_length=100)),
                ('ExteriorApproval', models.BooleanField(default=False)),
                ('InteriorApproval', models.BooleanField(default=False)),
                ('HoodApproval', models.BooleanField(default=False)),
                ('TrunkApproval', models.BooleanField(default=False)),
                ('Other', models.CharField(max_length=140)),
                ('Verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('waiverID', models.CharField(max_length=34, primary_key=True, serialize=False)),
                ('waiverDate', models.CharField(max_length=30)),
                ('waiverComplete', models.CharField(max_length=100)),
                ('UUID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('VIN', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('vehicleYear', models.IntegerField(validators=[pages.db_validators.validate_car_year])),
                ('vehicleMake', models.CharField(max_length=50)),
                ('vehicleModel', models.CharField(max_length=50)),
                ('UUID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('inspectionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.inspection')),
            ],
        ),
        migrations.AddField(
            model_name='inspection',
            name='VIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.vehicle'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('imageID', models.CharField(max_length=34, primary_key=True, serialize=False)),
                ('waiverID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.waiver')),
            ],
        ),
        migrations.AddField(
            model_name='tiuser',
            name='VIN',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.vehicle'),
        ),
        migrations.AddField(
            model_name='tiuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='tiuser',
            name='imageID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.image'),
        ),
        migrations.AddField(
            model_name='tiuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='tiuser',
            name='waiverID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.waiver'),
        ),
    ]
