# Generated by Django 3.1.1 on 2020-10-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enc_pswd',
            field=models.CharField(default='', max_length=12),
        ),
    ]
