# Generated by Django 3.1.2 on 2020-11-16 03:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='waiver',
            old_name='waiverComplete',
            new_name='waiverName',
        ),
        migrations.RemoveField(
            model_name='tiuser',
            name='imageID',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='tiuser',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imageID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspectionID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='inspectionID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.inspection'),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='waiverDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='waiverID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
