# Generated by Django 3.1.1 on 2020-10-22 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20201022_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='VIN',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.vehicle'),
        ),
        migrations.AddField(
            model_name='user',
            name='imageID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.image'),
        ),
        migrations.AddField(
            model_name='user',
            name='waiverID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.waiver'),
        ),
    ]
