# Generated by Django 3.1.2 on 2020-11-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_vehicle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='optionalExteriorPhoto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='optionalHUTPhoto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='optionalHelmetPhoto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='optionalInteriorPhoto',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='tiuser',
            name='isTI',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicleType',
            field=models.CharField(choices=[('Ineligible', 'Ineligible'), ('A Street', 'A Street'), ('B Street', 'B Street'), ('C Street', 'C Street'), ('D Street', 'D Street'), ('E Street', 'E Street'), ('F Street', 'F Street'), ('G Street', 'G Street'), ('H Street', 'H Street'), ('Super Street', 'Super Street')], default='IN', max_length=12),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='tiuser',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicleAvatar',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='waiver',
            name='waiverName',
            field=models.CharField(default='Full name', max_length=100),
        ),
    ]
